name: flutter_facebook_sdk
description: A flutter plugin to get facebook deep links and log app events using the latest Facebook SDK to include support for iOS 14
version: 1.3.8
homepage: https://github.com/saadfarhan124/flutter_facebook_sdk

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterFacebookSdkPlugin
        package: saad.farhan.flutter_facebook_sdk
      ios:
        pluginClass: FlutterFacebookSdkPlugin
